/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nacho
 */
public class InsertClientMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public InsertClientMenu() {
        initComponents();
        this.setSize(995, 650);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackgroundLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ClientType = new javax.swing.JComboBox<>();
        CedulaText = new javax.swing.JTextField();
        NombreText = new javax.swing.JTextField();
        DireccionText = new javax.swing.JTextField();
        CiudadText = new javax.swing.JTextField();
        NumeroText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AppTitle_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 0, 290, 240);

        BackgroundLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background1.jpg"))); // NOI18N
        getContentPane().add(BackgroundLabel1);
        BackgroundLabel1.setBounds(-20, -290, 1020, 450);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 160, 180);

        InsertButton.setBackground(new java.awt.Color(213, 213, 213));

        InsertButton.setForeground(new java.awt.Color(4, 83, 125));
        InsertButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        InsertButton.setForeground(new java.awt.Color(4, 83, 125));
        InsertButton.setText("Insertar");
        InsertButton.setToolTipText("");
        InsertButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertButton);
        InsertButton.setBounds(540, 530, 170, 50);

        ExitButton.setBackground(new java.awt.Color(213, 213, 213));
        ExitButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(4, 83, 125));
        ExitButton.setText("Atrás");
        ExitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(10, 550, 170, 50);

        ClientType.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        ClientType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Organización" }));
        ClientType.setToolTipText("");
        ClientType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ClientTypeItemStateChanged(evt);
            }
        });
        ClientType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientTypeActionPerformed(evt);
            }
        });
        getContentPane().add(ClientType);
        ClientType.setBounds(260, 380, 140, 30);

        CedulaText.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        CedulaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CedulaText.setToolTipText("");
        CedulaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTextActionPerformed(evt);
            }
        });
        getContentPane().add(CedulaText);
        CedulaText.setBounds(420, 300, 200, 30);

        NombreText.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        NombreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreText.setToolTipText("");
        getContentPane().add(NombreText);
        NombreText.setBounds(630, 300, 200, 30);

        DireccionText.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        DireccionText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DireccionText.setToolTipText("");
        getContentPane().add(DireccionText);
        DireccionText.setBounds(630, 380, 200, 30);

        CiudadText.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        CiudadText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CiudadText.setToolTipText("");
        getContentPane().add(CiudadText);
        CiudadText.setBounds(420, 380, 200, 30);

        NumeroText.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        NumeroText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumeroText.setText("*Solo aplica para persona*");
        NumeroText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroTextActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroText);
        NumeroText.setBounds(520, 450, 200, 30);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 83, 125));
        jLabel4.setText("Insertar Cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 350, 220, 70);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 83, 125));
        jLabel5.setText("Tipo de Cliente");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 340, 110, 40);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 83, 125));
        jLabel6.setText("Ciudad");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 340, 60, 40);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(4, 83, 125));
        jLabel7.setText("Cédula");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 260, 50, 40);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(4, 83, 125));
        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(700, 260, 60, 40);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(4, 83, 125));
        jLabel9.setText("Dirección");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(700, 340, 70, 40);

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(4, 83, 125));
        jLabel10.setText("Teléfono");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 410, 70, 40);

        BackgroundLabel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundLabel.setOpaque(true);
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 160, 1020, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void ClientTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientTypeActionPerformed

    private void ClientTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ClientTypeItemStateChanged
        // TODO add your handling code here:
        if(this.ClientType.getSelectedIndex() == 0){
            this.NumeroText.setEnabled(true);
        }
        else{
            this.NumeroText.setEnabled(false);
        }
    }//GEN-LAST:event_ClientTypeItemStateChanged

    private void CedulaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTextActionPerformed

    private void NumeroTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertClientMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BackgroundLabel1;
    public javax.swing.JTextField CedulaText;
    public javax.swing.JTextField CiudadText;
    public javax.swing.JComboBox<String> ClientType;
    public javax.swing.JTextField DireccionText;
    public javax.swing.JButton ExitButton;
    public javax.swing.JButton InsertButton;
    public javax.swing.JTextField NombreText;
    public javax.swing.JTextField NumeroText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
