/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nacho
 */
public class PartMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public PartMenu() {
        initComponents();
        this.setSize(995, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackgroundLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProviderButton = new javax.swing.JButton();
        InsertButton = new javax.swing.JButton();
        VehicleButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        PreciosButton = new javax.swing.JButton();
        ListPartButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        DeleteButton.setBackground(new java.awt.Color(213, 213, 213));
        DeleteButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(4, 83, 125));
        DeleteButton.setText("Borrar");
        DeleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton);
        DeleteButton.setBounds(410, 390, 190, 50);
        DeleteButton.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AppTitle_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 0, 290, 240);

        BackgroundLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background1.jpg"))); // NOI18N
        getContentPane().add(BackgroundLabel1);
        BackgroundLabel1.setBounds(-20, -290, 1020, 450);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Tool.png"))); // NOI18N
        jLabel3.setAutoscrolls(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 160, 180);

        ProviderButton.setBackground(new java.awt.Color(213, 213, 213));
        ProviderButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        ProviderButton.setForeground(new java.awt.Color(4, 83, 125));
        ProviderButton.setText("Proveedores");
        ProviderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProviderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProviderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ProviderButton);
        ProviderButton.setBounds(220, 310, 200, 50);

        InsertButton.setBackground(new java.awt.Color(213, 213, 213));
        InsertButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        InsertButton.setForeground(new java.awt.Color(4, 83, 125));
        InsertButton.setText("Insertar");
        InsertButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(InsertButton);
        InsertButton.setBounds(220, 390, 180, 50);

        VehicleButton.setBackground(new java.awt.Color(213, 213, 213));

        VehicleButton.setForeground(new java.awt.Color(4, 83, 125));
        VehicleButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        VehicleButton.setForeground(new java.awt.Color(4, 83, 125));
        VehicleButton.setText("Automóviles");
        VehicleButton.setToolTipText("");
        VehicleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VehicleButton);
        VehicleButton.setBounds(610, 310, 210, 50);

        ExitButton.setBackground(new java.awt.Color(213, 213, 213));
        ExitButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(4, 83, 125));
        ExitButton.setText("Exit");
        ExitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(430, 490, 170, 50);

        VehicleButton.setBackground(new java.awt.Color(213, 213, 213));

        VehicleButton.setForeground(new java.awt.Color(4, 83, 125));
        PreciosButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        PreciosButton.setForeground(new java.awt.Color(4, 83, 125));
        PreciosButton.setText("Precios");
        PreciosButton.setToolTipText("");
        VehicleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PreciosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreciosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PreciosButton);
        PreciosButton.setBounds(620, 390, 200, 50);

        VehicleButton.setBackground(new java.awt.Color(213, 213, 213));

        VehicleButton.setForeground(new java.awt.Color(4, 83, 125));
        ListPartButton.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        ListPartButton.setForeground(new java.awt.Color(4, 83, 125));
        ListPartButton.setText("Listar");
        ListPartButton.setToolTipText("");
        VehicleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListPartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ListPartButton);
        ListPartButton.setBounds(430, 310, 160, 50);

        BackgroundLabel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundLabel.setOpaque(true);
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 160, 1020, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ProviderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProviderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProviderButtonActionPerformed

    private void VehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void PreciosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreciosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreciosButtonActionPerformed

    private void ListPartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListPartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BackgroundLabel1;
    public javax.swing.JButton DeleteButton;
    public javax.swing.JButton ExitButton;
    public javax.swing.JButton InsertButton;
    public javax.swing.JButton ListPartButton;
    public javax.swing.JButton PreciosButton;
    public javax.swing.JButton ProviderButton;
    public javax.swing.JButton VehicleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
